# permissions for end users to edit dpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dpu-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpu-network-operator
    app.kubernetes.io/part-of: dpu-network-operator
    app.kubernetes.io/managed-by: kustomize
  name: dpu-editor-role
rules:
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dpu.openshift.io
  resources:
  - dpus/status
  verbs:
  - get
